# syntax=docker/dockerfile:1
FROM debian:bullseye

RUN set -x ; \
    apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends build-essential curl

RUN set -x ; \
    apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3 python3-dev python3-wheel python3-venv libpq-dev libldap2-dev libsasl2-dev

RUN python3 -m venv --upgrade-deps /venv

RUN curl -sSL https://raw.githubusercontent.com/odoo/odoo/master/requirements.txt -o /tmp/odoo-requirements.txt \
    && . /venv/bin/activate \
    && pip install --no-cache-dir -r /tmp/odoo-requirements.txt websocket-client inotify dbfread google_auth pdfminer.six phonenumbers \
    && rm /tmp/odoo-requirements.txt

ARG CHROME_URL=https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_101.0.4951.64-1_amd64.deb
RUN curl -sSL $CHROME_URL -o /tmp/chrome.deb \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends /tmp/chrome.deb \
    && rm /tmp/chrome.deb
#RUN set -x ; \
#    apt-get update \
#    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends chromium

VOLUME /src
VOLUME /data

WORKDIR /src

EXPOSE 8069

ENTRYPOINT [ \
    "/venv/bin/python", "odoo/odoo-bin", \
        "--workers", "0", \
        "--max-cron-threads", "0", \
        "--data-dir", "/data", \
        "--db_host", "localhost", \
        "--db_user", "odoo", \
        "--db_password", "odoo" \
]
