#!/usr/bin/env bash

# PastBoard aliases
if [[ -n  "$WAYLAND_DISPLAY" ]]; then
    alias pbcopy="wl-copy"
    alias pbpaste="wl-paste"
else
    alias pbcopy="xsel --clipboard --in"
    alias pbpaste="xsel --clipboard --out"
fi
